version: 0.2

env:
  variables:
    TEMPLATE_DIR: template
    S3_BUCKET: my-basic-cft-bucket

phases:
  build:
    commands:
      - echo "Uploading templates to S3"
      - aws s3 cp $TEMPLATE_DIR s3://$S3_BUCKET/templates/ --recursive
